### PR TITLE
Expose changeZoom and changePan APIs

### PR DESCRIPTION
**Pull request by el**
We have a way to `resetZoom` but we dont have a way to change the zoom and pan. This PR exposes `doPan` and `doZoom` functions.

Sample usecase: https://codepen.io/elizzk/pen/OJMZMEm

### CODE REVIEW

**Comment by lcoenen-jci** [comment]
Hey that would be cool to be merged! I want to do something like this and without it I would have to use D3.

Koodos @el

**Comment by el** [comment]
@benmccann Can this be merged ?

**Comment by kurkle** [comment]
I think it would be best to export/expose those function in the plugin instead. We don't generally want to add to the chart instance.
It might require some refactoring.

**Comment by el** [comment]
> I think it would be best to export/expose those function in the plugin instead. We don't generally want to add to the chart instance.
> It might require some refactoring.

I exposed them the same way resetZoom was exposed. If this is exposed as part of the plugin, the same should be the case for the resetZoom function.

**Comment by kurkle** [comment]
> I exposed them the same way resetZoom was exposed. If this is exposed as part of the plugin, the same should be the case for the resetZoom function.

Exactly :)

**Pull request closed without merging**
