### PR TITLE
Fix drag-to-zoom on Firefox and other browsers

### LINKED ISSUE #62: Zooming on Firefox
Hello,

I don't know if it a known issue but I can not Drag to Zoom using Firefox. 

Heres an example: http://codepen.io/anon/pen/GrQemG

When running on Chrome the zoom works but if you run it on Firefox it doesn't.

My firefox version is 51.0.1+build2-0ubuntu0.16.04.1

There is something that I can do to make it work on both Firefox and Chrome?

Kind regards and thank you for the plugin

### PR DESCRIPTION
**Pull request by AlbinoDrought**
Use event.clientX instead of just event.x, a property that doesn't exist on some browsers

Fixes #62

See https://developer.mozilla.org/en/docs/Web/Events/click

### CODE REVIEW

**Comment by PedroPovedaQ** [comment]
Is no one going to merge this in?

**Comment by AlbinoDrought** [comment]
Compiled/bundled versions can be found in my branch if wanted:

https://github.com/AlbinoDrought/chartjs-plugin-zoom/blob/firefox-drag-x/chartjs-plugin-zoom.js

https://github.com/AlbinoDrought/chartjs-plugin-zoom/blob/firefox-drag-x/chartjs-plugin-zoom.min.js

**Comment by PedroPovedaQ** [comment]
Thank you!

**Comment by etimberg** [comment]
Looks good to me. @compwright have you had a chance to look at this?

**Pull request merged**
