### PR TITLE
Refactor to logical entities

### PR DESCRIPTION
**Pull request by kurkle**
image

### CODE REVIEW

**Comment by kurkle** [comment]
**Size Change:** -127 B (-1%) 

**Total Size:** 15.4 kB

| Filename | Size | Change |
| :--- | :---: | :---: |
| `dist/chartjs-plugin-zoom.esm.js` | 5.83 kB | -72 B (-1%) |
| `dist/chartjs-plugin-zoom.js` | 6.09 kB | -76 B (-1%) |
| `dist/chartjs-plugin-zoom.min.js` | 3.46 kB | +21 B (+1%) |

**Comment by kurkle** [comment]
I'll try something to get a better diff, this is a huge review.

**Review by etimberg — DISMISSED** [review]

**Review by jledentu — CHANGES_REQUESTED** [review]
Awesome refactoring! 👏 

I've found an issue in the `zoom-time` sample. The chart disappears when dragging, and there are console errors:

```
Uncaught TypeError: chartInstance.$zoom._options is undefined
    beforeDatasetsDraw http://127.0.0.1:8080/dist/chartjs-plugin-zoom.js:688
    callback http://127.0.0.1:8080/node_modules/chart.js/dist/chart.js:796
    ...
```

**Comment by kurkle** [comment]
Thanks @jledentu, did not go through the samples myself. I had not completed the beforeDatasetsDraw hook refactoring. 
Completed that and finalized var => let/const changes.

**Review by jledentu — APPROVED** [review]
Looks good to me, congrats

**Pull request merged**
