### PR TITLE
Replace script tags with script+SRI

### PR DESCRIPTION
**Pull request by jacopotediosi**
Please see issue #426

### CODE REVIEW

**Comment by benmccann** [comment]
Is it possible to add the `integrity` attribute without adding `/dist/Chart.min.js` in the `src`?

**Comment by jacopotediosi** [comment]
> Is it possible to add the `integrity` attribute without adding `/dist/Chart.min.js` in the `src`?

Of course, but please note that if the CDN maintainer changes the default file (for example, it sets the .js file instead of the .min.js one) the integrity will no longer be valid (because the hash was calculated for the original file) and all the sites where the script was included will be broken (such an action would still be very impactful and risky even without SRI, and this is why in all my sites I specify the exact file I intend to include).

**Comment by benmccann** [comment]
That seems unlikely to be much of a risk since we're using a versioned package

**Comment by kurkle** [comment]
I think it would be better to write some instructions, that do not include maintenance overhead here, when updating versions.
Its bad practice to copy the SRI from anywhere else than the CDN you are relying on.

**Comment by jacopotediosi** [comment]
> I think it would be better to write some instructions, that do not include maintenance overhead here, when updating versions.
> Its bad practice to copy the SRI from anywhere else than the CDN you are relying on.

Clicking "Copy HTML" button on jsdeliver.net writes the complete SRI hash tag to the clipboard, so I don't see too much overhead. Please note that if the SRI hash doesn't match the file pointed by src url (eg you copied it from a bad site which is trying to do something malicious) the browser will refuse to load the script. So the best practice is to check the correctness of the src; there are no security problems if you copy the SRI from places other than the CDN.

**Comment by kurkle** [comment]
Yeah, its easy to get the SRI from the CDN, once the package is published and available from the CDN.
The version needs to be updated when a new release is published. Ideally everything is updated before the new version is published. Either calculating the SRI from build or updating the README after release, in my opinion counts for maintenance overhead. 

If we decided to add the SRI to script tags in docs, it should of course be applied to all repositories under chartjs.

**Comment by etimberg** [comment]
If we can find a way to autogenerate this, that'd be the best solution in my opinion. I agree with @kurkle that this adds some maintenance burden for new releases that can only be done after the code is tagged, so the changes won't be in the actual release tag.

**Comment by kurkle** [comment]
Closing. If you find an way to autogenerate those when releasing to NPM, happy to take another look.

**Pull request closed without merging**
