### PR TITLE
Solves issue #81 (Zoom is zooming in the wrong direction)

### PR DESCRIPTION
**Pull request by matonga**
Solves issue #81
https://github.com/chartjs/chartjs-plugin-zoom/issues/81

### CODE REVIEW

**Comment by etimberg** [comment]
@matonga could you create a fiddle that demonstrates this fix?

**Comment by matonga** [comment]
@etimberg here you are: https://codepen.io/anon/pen/XgqjNe

**Comment by etimberg** [comment]
@matonga zoom doesn't appear to be working in that fiddle

**Comment by matonga** [comment]
Sorry, my fault (problems with file hosting). Please try again now.

**Comment by adeel3612** [comment]
@matonga did your commits passed through the plugin i mean did you commit the changes in the plugin files?

**Comment by benmccann** [comment]
The fiddle doesn't seem to be working

**Pull request merged**
