### PR TITLE
Check zoomLimits in time scales

### LINKED ISSUE #91: [Zoom-Limits] Limit zoom for time-chart
Limiting zooming for x-Axis is not yet implemented, when using a time-chart (as stated in README.md).
I added this for my own application. Maybe it is helpful. I'll add a PR for that.

### PR DESCRIPTION
**Pull request by meisterlampe**
I made this minor change to get x-axis-zoom-limits for chart type time working in my project.
It closes #91 
May be it's of use for you. Feel free to edit or delete it :)

### CODE REVIEW

**Comment by louAddo** [comment]
Hi, I am trying to to add zoom limit for a chart type time I am developing. I am using your code and I am unsure on what to write on the config to get it to work. Should I be using rangeMax and rangeMin for this?

> zoom: {
>          enabled: true,
>          mode: 'x',
>          rangeMin: {
>             // Format of min zoom range depends on scale type
>             x: null,
>             y: null
>         },
>         rangeMax: {
>             // Format of max zoom range depends on scale type
>             x:  null,
>             y: null
>         }
> }
>

**Comment by benmccann** [comment]
@meisterlampe this seems very similar to your other PR https://github.com/chartjs/chartjs-plugin-zoom/pull/79 ?  Should we just review this one and close the other?

**Comment by benmccann** [comment]
Nevermind. I take back my comment about the PRs being very similar

**Comment by benmccann** [comment]
This PR needs to be rebased against recent changes

Sorry for the long delay in reviewing

**Comment by meisterlampe** [comment]
Merged everything. Is this ok now?

**Pull request merged**
