### PR TITLE
Fix listener setup

### PR DESCRIPTION
**Pull request by benmccann**
Closes https://github.com/chartjs/chartjs-plugin-zoom/pull/244 https://github.com/chartjs/chartjs-plugin-zoom/pull/196 https://github.com/chartjs/chartjs-plugin-zoom/issues/176 https://github.com/chartjs/chartjs-plugin-zoom/issues/77

### CODE REVIEW

**Comment by yogevyuval** [comment]
When zooming I get `Cannot read property '_originalOptions' of undefined` in `storeOriginalOptions` when using this commit (although maybe it's on the master as well - not sure)

**Comment by cooljeffro** [comment]
Seems like this doesn't account for when zoom.enabled = false

**Comment by benmccann** [comment]
@cooljeffro can you test https://github.com/chartjs/chartjs-plugin-zoom/pull/254

**Comment by cooljeffro** [comment]
Yea, that's working for me, thanks!

**Pull request merged**
