### PR TITLE
fix: trigger onZoom from zoomScale

### LINKED ISSUE #775: onZoom callbacks for zoomScale function
When using `zoomScale`, callbacks for zoom (onZoom etc.) are not triggered.

### PR DESCRIPTION
**Pull request by kurkle**
fix #775

### CODE REVIEW

**Comment by yubiuser** [comment]
This update broke our use case and I don't know how to mitigate the new behavior. We basically have the same situation as described as in https://github.com/chartjs/chartjs-plugin-zoom/issues/768:

We have a time series bar chart with only positive y-values. When zooming, y-axis should stay fixed at zero, because it does not make sense to lose the zero anchor. We basically used `onZoom` to trigger `chart.zoomScale` to set the new scale with fixed y min to zero.

Screenshot from 2024-11-19 17-40-09


But with this change, this causes an endless loop. Any idea how to circumvent this?

Old code

```
      onZoom: function ({ chart }) {
        // The first time the chart is zoomed, save the maximum initial scale bound
        if (!chart.absMax) chart.absMax = chart.getInitialScaleBounds().y.max;
        // Calculate the maximum value to be shown for the current zoom level
        const zoomMax = chart.absMax / chart.getZoomLevel();
        // Update the y axis scale
        chart.zoomScale("y", { min: 0, max: zoomMax }, "default");
        // Update the y axis ticks and round values to natural numbers
        chart.options.scales.y.ticks.callback = function (value) {
          return value.toFixed(0);
        };
```

**Comment by kurkle** [comment]
Instead of calling zoomScale from onZoom, just specify `min: 0` in the y-scale options?

**Comment by yubiuser** [comment]
> Instead of calling zoomScale from onZoom, just specify min: 0 in the y-scale options?

This does not work, as it specifies the minimum, but not the maximal minimum (it doesn't get negative).
___
```
chart.options.scales.y.min = 0;
chart.options.scales.y.max = chart.absMax / chart.getZoomLevel(); // probably not needed
chart.update();
```

This works, but gives an unpleasant scale jump
Peek 2024-11-20 07-49

Before it was smooth
Peek 2024-11-20 07-55

**Comment by kurkle** [comment]
maybe `chart.update('none')` produces similar result?

**Comment by yubiuser** [comment]
Yes, but now I can only zoom in, and not zoom out again.

```
      onZoom: function ({ chart }) {
        chart.options.scales.y.min = 0;
        chart.update('none');
        }
```

**Comment by kurkle** [comment]
I've created #901 for letting you do something like:

```js
      onZoom: function ({ chart, trigger }) {
        if (trigger === 'api') {
          // Ignore onZoom triggered by the chart.zoomScale api call below
          return;
        }
        // The first time the chart is zoomed, save the maximum initial scale bound
        if (!chart.absMax) chart.absMax = chart.getInitialScaleBounds().y.max;
        // Calculate the maximum value to be shown for the current zoom level
        const zoomMax = chart.absMax / chart.getZoomLevel();
        // Update the y axis scale
        chart.zoomScale("y", { min: 0, max: zoomMax }, "default");
        // Update the y axis ticks and round values to natural numbers
        chart.options.scales.y.ticks.callback = function (value) {
          return value.toFixed(0);
        };
```

**Comment by yubiuser** [comment]
Perfect. Tested it locally compiled and it works like charm.

Peek 2024-11-23 09-10

**Pull request merged**
