### PR TITLE
Fix non-zoomable charts eating scroll events

### PR DESCRIPTION
**Pull request by jacopotediosi**

### CODE REVIEW

**Comment by kurkle** [comment]
You need to fix these lint errorrs:

> [test-lint]   477:1   error    Trailing spaces not allowed                                                 no-trailing-spaces
> [test-lint]   533:9   error    'zoomOptions' is already declared in the upper scope                        no-shadow
> [test-lint]   567:9   error    'panOptions' is already declared in the upper scope                         no-shadow

**Comment by kurkle** [comment]
Needs a rebase too (tabs to spaces change)

**Comment by jacopotediosi** [comment]
> Needs a rebase too (tabs to spaces change)

Done

**Comment by kurkle** [comment]
Thanks, looks like the eslint config is a bit strict:

> 334:10  error    Method 'start' has too many statements (34). Maximum allowed is 30  max-statements

Could you add `max-statements: ["warn", 30]` under the `rules` in .eslintrc.yml?

**Comment by jacopotediosi** [comment]
> Thanks, looks like the eslint config is a bit strict:
> 
> > 334:10  error    Method 'start' has too many statements (34). Maximum allowed is 30  max-statements
> 
> Could you add `max-statements: ["warn", 30]` under the `rules` in .eslintrc.yml?

Done

**Review by kurkle — APPROVED** [review]

**Comment by kurkle** [comment]
Thanks @jacopotediosi

**Pull request merged**
