### PR TITLE
Feature: Zoom each scale separately

### PR DESCRIPTION
**Pull request by lirik90**
Added the **overScaleMode** option so that you can use zoom and pan separately for each scale when the mouse is over the scale.
Try it: https://codepen.io/lirik90/pen/rNLqMVg
Or watch what is it: https://youtu.be/u3HlB3YX_fs

### CODE REVIEW

**Review by kurkle — COMMENTED** [review]
Needs a rebase + added some comments

**Comment by lirik90** [comment]
Hi, @kurkle . I tried to add a comment, please see it.

**Comment by kurkle** [comment]
Thanks, the code looks good to me now. Would you be able to create a test for it?

**Comment by lirik90** [comment]
I added two small tests. Are they enough?

**Review by kurkle — APPROVED** [review]

**Pull request merged**
