### PR TITLE
Added onZoom and onPan callbacks for their respective configs; #130

### PR DESCRIPTION
**Pull request by buddyp450**

### CODE REVIEW

**Comment by benmccann** [comment]
@buddyp450 can you add to documentation on README as well?

**Comment by FallenRiteMonk** [comment]
This would be really important for me!
@benmccann could you please merge and release this as fast as possible?
I would really appreciate it and would even create a PR for a short documentation if you would like!

**Comment by benmccann** [comment]
@FallenRiteMonk sure if you sent a PR for documentation and link it to this one I can take a look at merging them together

**Comment by FallenRiteMonk** [comment]
@benmccann Thanks for merging. Could you please bump a new release, as the current latest does not contain this PR?

**Comment by Techn1x** [comment]
@benmccann gentle reminder to publish a release for this :) doZoom and doPan are in the readme, and I was on the latest published version, so I went to use them and was scratching my head for a little while wondering why they didn't work

**Comment by benmccann** [comment]
I released 0.6.6

**Pull request merged**
